In [1]:
import bs4
import requests
import pandas as pd

In [2]:
def amazon_footwear(url,header,no_of_page=1):
    
    footwear = {
    'Brand' : [],
    'Category' : [],
    'Rating' : [],
    'price':[],
    'Original_price':[],
    'Save':[]
    }
    
    for i in range(1,no_of_page+1):
        response = requests.get(url.format(i,i), headers=header)
        soup = bs4.BeautifulSoup(response.content,'html.parser')
        
        if response.status_code == 200:
        
            divs = soup.find_all('div',attrs={'class':'sg-col-4-of-12 s-result-item s-asin sg-col-4-of-16 sg-col sg-col-4-of-20'})

            for div in divs:
                product = div.find('div',attrs={'class':'a-section a-spacing-none'})

                try :
                    if product.find('div',attrs={'class':"a-row a-size-small"}).span.text.strip():
                        pass
                    price = product.find_all('span',attrs={'class':"a-offscreen"})
                    if price[1].text.strip():
                        pass
                except:
                    continue

                footwear['Brand'].append(product.find('h5',attrs={'class':"s-line-clamp-1"}).text.strip())
                footwear['Category'].append(product.find('h2',attrs={'class':"a-size-mini a-spacing-none a-color-base s-line-clamp-2"}).text.strip())
                footwear['Rating'].append(product.find('div',attrs={'class':"a-row a-size-small"}).span.text.strip())
                price = product.find_all('span',attrs={'class':"a-offscreen"})
                footwear['price'].append(price[0].text.strip())
                footwear['Original_price'].append(price[1].text.strip())
                footwear['Save'].append('Save '+ product.find('div',attrs={'class':'a-row a-size-base a-color-base'}).text.split('Save')[-1].strip())

            
        else:
            print(response.status_code,'Reason :',response.reason)
        
        print('Page_no :',i,'Scrapped')
    footwear = pd.DataFrame(footwear)

    return footwear

In [13]:
context = {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.5',
    'Host': 'www.amazon.in',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0'
}
url = 'https://www.amazon.in/s?k=footwear&i=shoes&rh=n%3A1983396031%2Cn%3A1983575031&dc&page={}&qid=1627375238&rnid=3576079031&ref=sr_pg_{}'
    

footwear = amazon_footwear(url,context,350)

Page_no : 1 Scrapped
Page_no : 2 Scrapped
Page_no : 3 Scrapped
Page_no : 4 Scrapped
Page_no : 5 Scrapped
Page_no : 6 Scrapped
Page_no : 7 Scrapped
Page_no : 8 Scrapped
Page_no : 9 Scrapped
Page_no : 10 Scrapped
Page_no : 11 Scrapped
Page_no : 12 Scrapped
Page_no : 13 Scrapped
Page_no : 14 Scrapped
Page_no : 15 Scrapped
Page_no : 16 Scrapped
Page_no : 17 Scrapped
Page_no : 18 Scrapped
Page_no : 19 Scrapped
Page_no : 20 Scrapped
Page_no : 21 Scrapped
Page_no : 22 Scrapped
Page_no : 23 Scrapped
Page_no : 24 Scrapped
Page_no : 25 Scrapped
Page_no : 26 Scrapped
Page_no : 27 Scrapped
Page_no : 28 Scrapped
Page_no : 29 Scrapped
Page_no : 30 Scrapped
Page_no : 31 Scrapped
Page_no : 32 Scrapped
Page_no : 33 Scrapped
Page_no : 34 Scrapped
Page_no : 35 Scrapped
Page_no : 36 Scrapped
Page_no : 37 Scrapped
Page_no : 38 Scrapped
Page_no : 39 Scrapped
Page_no : 40 Scrapped
Page_no : 41 Scrapped
Page_no : 42 Scrapped
Page_no : 43 Scrapped
Page_no : 44 Scrapped
Page_no : 45 Scrapped
Page_no : 46 Scrapped
Page_no : 47 Scrapped
Page_no : 48 Scrapped
Page_no : 49 Scrapped
Page_no : 50 Scrapped
Page_no : 51 Scrapped
Page_no : 52 Scrapped
Page_no : 53 Scrapped
Page_no : 54 Scrapped
Page_no : 55 Scrapped
Page_no : 56 Scrapped
Page_no : 57 Scrapped
Page_no : 58 Scrapped
Page_no : 59 Scrapped
Page_no : 60 Scrapped
Page_no : 61 Scrapped
Page_no : 62 Scrapped
Page_no : 63 Scrapped
Page_no : 64 Scrapped
Page_no : 65 Scrapped
Page_no : 66 Scrapped
Page_no : 67 Scrapped
Page_no : 68 Scrapped
Page_no : 69 Scrapped
Page_no : 70 Scrapped
Page_no : 71 Scrapped
Page_no : 72 Scrapped
Page_no : 73 Scrapped
Page_no : 74 Scrapped
Page_no : 75 Scrapped
Page_no : 76 Scrapped
Page_no : 77 Scrapped
Page_no : 78 Scrapped
Page_no : 79 Scrapped
Page_no : 80 Scrapped
Page_no : 81 Scrapped
Page_no : 82 Scrapped
Page_no : 83 Scrapped
Page_no : 84 Scrapped
Page_no : 85 Scrapped
Page_no : 86 Scrapped
Page_no : 87 Scrapped
Page_no : 88 Scrapped
Page_no : 89 Scrapped
Page_no : 90 Scrapped
Page_no : 91 Scrapped
Page_no : 92 Scrapped
Page_no : 93 Scrapped
Page_no : 94 Scrapped
Page_no : 95 Scrapped
Page_no : 96 Scrapped
Page_no : 97 Scrapped
Page_no : 98 Scrapped
Page_no : 99 Scrapped
Page_no : 100 Scrapped
Page_no : 101 Scrapped
Page_no : 102 Scrapped
Page_no : 103 Scrapped
Page_no : 104 Scrapped
Page_no : 105 Scrapped
Page_no : 106 Scrapped
Page_no : 107 Scrapped
Page_no : 108 Scrapped
Page_no : 109 Scrapped
Page_no : 110 Scrapped
Page_no : 111 Scrapped
Page_no : 112 Scrapped
Page_no : 113 Scrapped
Page_no : 114 Scrapped
Page_no : 115 Scrapped
Page_no : 116 Scrapped
Page_no : 117 Scrapped
Page_no : 118 Scrapped
Page_no : 119 Scrapped
Page_no : 120 Scrapped
Page_no : 121 Scrapped
Page_no : 122 Scrapped
Page_no : 123 Scrapped
Page_no : 124 Scrapped
Page_no : 125 Scrapped
Page_no : 126 Scrapped
Page_no : 127 Scrapped
Page_no : 128 Scrapped
Page_no : 129 Scrapped
Page_no : 130 Scrapped
Page_no : 131 Scrapped
Page_no : 132 Scrapped
Page_no : 133 Scrapped
Page_no : 134 Scrapped
Page_no : 135 Scrapped
Page_no : 136 Scrapped
Page_no : 137 Scrapped
Page_no : 138 Scrapped
Page_no : 139 Scrapped
Page_no : 140 Scrapped
Page_no : 141 Scrapped
Page_no : 142 Scrapped
Page_no : 143 Scrapped
Page_no : 144 Scrapped
Page_no : 145 Scrapped
Page_no : 146 Scrapped
Page_no : 147 Scrapped
Page_no : 148 Scrapped
Page_no : 149 Scrapped
Page_no : 150 Scrapped
Page_no : 151 Scrapped
Page_no : 152 Scrapped
Page_no : 153 Scrapped
Page_no : 154 Scrapped
Page_no : 155 Scrapped
Page_no : 156 Scrapped
Page_no : 157 Scrapped
Page_no : 158 Scrapped
Page_no : 159 Scrapped
Page_no : 160 Scrapped
Page_no : 161 Scrapped
Page_no : 162 Scrapped
Page_no : 163 Scrapped
Page_no : 164 Scrapped
Page_no : 165 Scrapped
Page_no : 166 Scrapped
Page_no : 167 Scrapped
Page_no : 168 Scrapped
Page_no : 169 Scrapped
Page_no : 170 Scrapped
Page_no : 171 Scrapped
Page_no : 172 Scrapped
Page_no : 173 Scrapped
Page_no : 174 Scrapped
Page_no : 175 Scrapped
Page_no : 176 Scrapped
Page_no : 177 Scrapped
Page_no : 178 Scrapped
Page_no : 179 Scrapped
Page_no : 180 Scrapped
Page_no : 181 Scrapped
Page_no : 182 Scrapped
Page_no : 183 Scrapped
Page_no : 184 Scrapped
Page_no : 185 Scrapped
Page_no : 186 Scrapped
Page_no : 187 Scrapped
Page_no : 188 Scrapped
Page_no : 189 Scrapped
Page_no : 190 Scrapped
Page_no : 191 Scrapped
Page_no : 192 Scrapped
Page_no : 193 Scrapped
Page_no : 194 Scrapped
Page_no : 195 Scrapped
Page_no : 196 Scrapped
Page_no : 197 Scrapped
Page_no : 198 Scrapped
Page_no : 199 Scrapped
Page_no : 200 Scrapped
Page_no : 201 Scrapped
Page_no : 202 Scrapped
Page_no : 203 Scrapped
Page_no : 204 Scrapped
Page_no : 205 Scrapped
Page_no : 206 Scrapped
Page_no : 207 Scrapped
Page_no : 208 Scrapped
Page_no : 209 Scrapped
Page_no : 210 Scrapped
Page_no : 211 Scrapped
Page_no : 212 Scrapped
Page_no : 213 Scrapped
Page_no : 214 Scrapped
Page_no : 215 Scrapped
Page_no : 216 Scrapped
Page_no : 217 Scrapped
Page_no : 218 Scrapped
Page_no : 219 Scrapped
Page_no : 220 Scrapped
Page_no : 221 Scrapped
Page_no : 222 Scrapped
Page_no : 223 Scrapped
Page_no : 224 Scrapped
Page_no : 225 Scrapped
Page_no : 226 Scrapped
Page_no : 227 Scrapped
Page_no : 228 Scrapped
Page_no : 229 Scrapped
Page_no : 230 Scrapped
Page_no : 231 Scrapped
Page_no : 232 Scrapped
Page_no : 233 Scrapped
Page_no : 234 Scrapped
Page_no : 235 Scrapped
Page_no : 236 Scrapped
Page_no : 237 Scrapped
Page_no : 238 Scrapped
Page_no : 239 Scrapped
Page_no : 240 Scrapped
Page_no : 241 Scrapped
Page_no : 242 Scrapped
Page_no : 243 Scrapped
Page_no : 244 Scrapped
Page_no : 245 Scrapped
Page_no : 246 Scrapped
Page_no : 247 Scrapped
Page_no : 248 Scrapped
Page_no : 249 Scrapped
Page_no : 250 Scrapped
Page_no : 251 Scrapped
Page_no : 252 Scrapped
Page_no : 253 Scrapped
Page_no : 254 Scrapped
Page_no : 255 Scrapped
Page_no : 256 Scrapped
Page_no : 257 Scrapped
Page_no : 258 Scrapped
Page_no : 259 Scrapped
Page_no : 260 Scrapped
Page_no : 261 Scrapped
Page_no : 262 Scrapped
Page_no : 263 Scrapped
Page_no : 264 Scrapped
Page_no : 265 Scrapped
Page_no : 266 Scrapped
Page_no : 267 Scrapped
Page_no : 268 Scrapped
Page_no : 269 Scrapped
Page_no : 270 Scrapped
Page_no : 271 Scrapped
Page_no : 272 Scrapped
Page_no : 273 Scrapped
Page_no : 274 Scrapped
Page_no : 275 Scrapped
Page_no : 276 Scrapped
Page_no : 277 Scrapped
Page_no : 278 Scrapped
Page_no : 279 Scrapped
Page_no : 280 Scrapped
Page_no : 281 Scrapped
Page_no : 282 Scrapped
Page_no : 283 Scrapped
Page_no : 284 Scrapped
Page_no : 285 Scrapped
Page_no : 286 Scrapped
Page_no : 287 Scrapped
Page_no : 288 Scrapped
Page_no : 289 Scrapped
Page_no : 290 Scrapped
Page_no : 291 Scrapped
Page_no : 292 Scrapped
Page_no : 293 Scrapped
Page_no : 294 Scrapped
Page_no : 295 Scrapped
Page_no : 296 Scrapped
Page_no : 297 Scrapped
Page_no : 298 Scrapped
Page_no : 299 Scrapped
Page_no : 300 Scrapped
Page_no : 301 Scrapped
Page_no : 302 Scrapped
Page_no : 303 Scrapped
Page_no : 304 Scrapped
Page_no : 305 Scrapped
Page_no : 306 Scrapped
Page_no : 307 Scrapped
Page_no : 308 Scrapped
Page_no : 309 Scrapped
Page_no : 310 Scrapped
Page_no : 311 Scrapped
Page_no : 312 Scrapped
Page_no : 313 Scrapped
Page_no : 314 Scrapped
Page_no : 315 Scrapped
Page_no : 316 Scrapped
Page_no : 317 Scrapped
Page_no : 318 Scrapped
Page_no : 319 Scrapped
Page_no : 320 Scrapped
Page_no : 321 Scrapped
Page_no : 322 Scrapped
Page_no : 323 Scrapped
Page_no : 324 Scrapped
Page_no : 325 Scrapped
Page_no : 326 Scrapped
Page_no : 327 Scrapped
Page_no : 328 Scrapped
Page_no : 329 Scrapped
Page_no : 330 Scrapped
Page_no : 331 Scrapped
Page_no : 332 Scrapped
Page_no : 333 Scrapped
Page_no : 334 Scrapped
Page_no : 335 Scrapped
Page_no : 336 Scrapped
Page_no : 337 Scrapped
Page_no : 338 Scrapped
Page_no : 339 Scrapped
Page_no : 340 Scrapped
Page_no : 341 Scrapped
Page_no : 342 Scrapped
Page_no : 343 Scrapped
Page_no : 344 Scrapped
Page_no : 345 Scrapped
Page_no : 346 Scrapped
Page_no : 347 Scrapped
Page_no : 348 Scrapped
Page_no : 349 Scrapped
Page_no : 350 Scrapped

In [14]:
footwear

,Brand,Category,Rating,price,Original_price,Save
0,PARAGON,Men's Flip Flops Thong Sandals,3.5 out of 5 stars,₹125,₹189,Save ₹64 (34%)
1,Sparx,Men's Sfg-564 Slipper,4.2 out of 5 stars,₹374,₹424,Save ₹50 (12%)
2,FLITE,Men's Flip Flops Thong Slippers,4.0 out of 5 stars,₹179,₹199,Save ₹20 (10%)
3,Sparx,Men's Flip-Flops and House Slippers,3.8 out of 5 stars,₹406,₹549,Save ₹143 (26%)
4,BATA,Men's Shrek Tr Slippers,4.0 out of 5 stars,₹479,₹799,Save ₹320 (40%)
...,...,...,...,...,...,...
6032,Bugatti,Men Grey Loafer Leather Flip-Flops,3.5 out of 5 stars,"₹2,394","₹5,499","Save ₹3,105 (56%)"
6033,BATA,Macho Men's Flip-Flops & Slipper,4.5 out of 5 stars,₹474,₹499,Save ₹25 (5%)
6034,Ipanema,Classica Brasil II AD FF,4.8 out of 5 stars,₹799,₹999,Save ₹200 (20%)
6035,BEONZA,Black Flip flop/ Slippers/ Slides for Boys and...,3.0 out of 5 stars,₹299,₹999,Save ₹700 (70%)
6036,Right Steps,Shock Absorbent | Lightweight | Slippers | Fli...,5.0 out of 5 stars,₹169,₹299,Save ₹130 (43%)

In [23]:
footwear.to_excel('Amazon_footwear.xlsx',index=False)

In [27]:
context = {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.5',
    'Host': 'www.amazon.in',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0'
}
url = 'https://www.amazon.in/s?k=shoes&page={}&qid=1627636153&ref=sr_pg_{}'
    

footwear = amazon_footwear(url,context,10)

Page_no : 1 Scrapped
Page_no : 2 Scrapped
Page_no : 3 Scrapped
Page_no : 4 Scrapped
Page_no : 5 Scrapped
Page_no : 6 Scrapped
Page_no : 7 Scrapped
Page_no : 8 Scrapped
Page_no : 9 Scrapped
Page_no : 10 Scrapped

In [28]:
footwear

,Brand,Category,Rating,price,Original_price,Save
0,CLYMB,Outdoor Sports Running Shoes for Mens Boy,3.0 out of 5 stars,₹329,₹999,Save ₹670 (67%)
1,Adidas,Men's Clinch-x M Running Shoe,3.9 out of 5 stars,"₹1,612","₹2,699","Save ₹1,087 (40%)"
2,Sparx,Men's Running Shoes,4.5 out of 5 stars,"₹1,049","₹1,399",Save ₹350 (25%)
3,WORLD WEAR FOOTWEAR,Men's (9212-9310) Multicolor Casual Sports Run...,2.8 out of 5 stars,₹499,₹998,Save ₹499 (50%)
4,ASIAN,Men's Wonder-13 Sports Running Shoes,4.0 out of 5 stars,₹549,₹599,Save ₹50 (8%)
...,...,...,...,...,...,...
271,Power,Men's Aero Running Shoes,4.1 out of 5 stars,₹936,"₹1,299",Save ₹363 (28%)
272,Nike,Men's Air Zoom Pegasus 38 Running Shoe,4.0 out of 5 stars,"₹8,985","₹9,995","Save ₹1,010 (10%)"
273,new balance,Men's Roav V1 Fresh Foam Running Shoe,4.7 out of 5 stars,"₹2,856","₹8,999","Save ₹6,143 (68%)"
274,Woodland,mens Sgc 3278919 Running Shoe,3.8 out of 5 stars,"₹1,617","₹2,795","Save ₹1,178 (42%)"
275,ASIAN,Men's Superfit Sports Running Shoes,3.9 out of 5 stars,₹508,₹599,Save ₹91 (15%)

In [ ]:
Sneakers
Sandals
Slippers
Loafers
boots
Flip-Flops
Mules